### ISSUE TITLE
Taiwanese

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#658] opened 2021-05-04 05:04 UTC
https://github.com/FutaGuard/FutaFilter

https://github.com/FutaGuard/FutaFilter/blob/master/hosts.txt

https://github.com/FutaGuard/FutaFilter/blob/master/nofarm_hosts.txt

**Comment by c2xusnpq6** [comment] 2021-05-16 11:56
@tasi788

**Comment by tasi788** [comment] 2021-05-16 11:57
ref: https://github.com/nextdns/metadata/issues/603

**Comment by c2xusnpq6** [comment] 2021-05-16 15:48
> ref: #603

反正nextdns在中國也被污染 搞不懂他們為什麼不要futafilter 他們又不像adguard像中國還能用.....(adguard這個你懂的~~~吧?)

**Comment by romaincointepas** [comment] 2021-06-12 11:27
Duplicate of https://github.com/nextdns/metadata/issues/603.

**Closed by romaincointepas** 2021-06-12 11:27 UTC
Labels: blocklist suggestion
