### ISSUE TITLE
Please add The Quantum Ad List

### ISSUE THREAD

**Issue by seannymurrs** [nextdns/metadata#501] opened 2020-12-21 01:33 UTC
https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list

**Comment by quantumpacket** [comment] 2020-12-21 20:26
@seannymurrs this is a duplicate of https://github.com/nextdns/metadata/issues/482

**Comment by romaincointepas** [comment] 2021-06-12 12:10
What @quantumpacket said.

**Closed by romaincointepas** 2021-06-12 12:10 UTC
