### ISSUE TITLE
netdna-ssl.com blocked by $third-party rule process

### ISSUE THREAD

**Issue by S-a-l-a-d** [nextdns/metadata#475] opened 2020-11-21 18:16 UTC
This rule is present in Liste FR. This domain is a CDN so I think it should be excluded.

**Comment by crssi** [comment] 2020-11-21 18:31
What does break when blocked?

**Comment by S-a-l-a-d** [comment] 2020-11-21 19:01
Microsoft blogs use it for static assets

- https://blogs.windows.com
- https://blogs.windows.com/msedgedev

**Comment by beerisgood** [comment] 2020-11-21 19:10
@S-a-l-a-d how does the site looks for you / without NextDNS?
For me it looks okay:
![image](https://user-images.githubusercontent.com/9625159/99885435-2b85a600-2c35-11eb-86d9-c7695250b0e5.png) 
![image](https://user-images.githubusercontent.com/9625159/99885445-448e5700-2c35-11eb-94e3-ea698d894b50.png)

Only `https://c.bing.com/c.gif?DI=4050&did=1&t=&CtsSyncId=48E8A5787AF94ABEA19E340FB69196CE&RedC=c1.microsoft.com&MXFR=07385F0EC46B66E021D35087C06B6034` get blocked for me on DNS level.

**Comment by S-a-l-a-d** [comment] 2020-11-21 19:19
@beerisgood As I reported, the rule is present in **Liste FR**, so you need to add it to reproduce.
![image](https://user-images.githubusercontent.com/5486625/99885608-ccda1f80-2c68-11eb-8350-2d616a057ad3.png)

Allowing `netdna-ssl.com` will make it look exactly like yours.

**Comment by crssi** [comment] 2020-11-21 21:18
It is best that you open an issue at https://forums.lanik.us/viewforum.php?f=91 

Cheers

Maybe a bit OT:
IMHO, I would ditch that list and use OISD, which includes `Liste FR` without your culprit `netdna-ssl.com`.
See https://oisd.nl/?p=inc

**Comment by S-a-l-a-d** [comment] 2020-11-22 08:01
@crssi The issue is not caused directly by Liste FR but the way NextDNS process the rules (like #19 or #368) so I decided to open this here. I just hope that this domain will be considered and whitelisted.

**Comment by crssi** [comment] 2020-11-22 10:31
That is completely unrelated since you are not visiting directly `netdna-ssl.com`.

The problem is `Liste FR`.
If `netdna-ssl.com` would be problematic, then it will be on many lists and not only on `Liste FR`, since it is not France geo oriented, but it is wide global... and again, the problem is `Liste FR`.

Additional to solution https://github.com/nextdns/metadata/issues/475#issuecomment-731638084 you can whitelist it.

**Comment by skapytek** [comment] 2020-11-24 23:06
The way nextdns using lists and transforming it to block certain domains is bullshit.
netdna-ssl.com$third-party=shouldnt be blocked by nextdns, also if its on a blocklist
abcxyz.netdna-ssl.com should be blocked if its on any kind of blocklist
And nextdns is blocking every domain which is included in a blocklist, no matter how the entry is shown in the blocklist.

**Comment by romaincointepas** [comment] 2020-11-27 01:37
This is definitely a good point and a valid question, I explained our approach to ABP-format blocklists [here](https://github.com/nextdns/metadata/issues/479#issuecomment-734526577).

I do find it weird though that `netdna-ssl.com` is only appearing in `Liste FR` out of all the blocklists. Is it really a tracking domain? Closing for now, happy to reopen if Liste FR decides to keep it.

**Closed by romaincointepas** 2020-11-27 01:37 UTC
