### ISSUE TITLE
Additional domain in Facebook service

### ISSUE THREAD

**Issue by jlapthorn** [nextdns/metadata#27] opened 2019-10-05 09:09 UTC
Can you add "fbcdn.net" to facebook  service

**Comment by romaincointepas** [comment] 2019-12-22 07:25
This could potentially break other Facebook-owned services like Instagram and Messenger, we will investigate.

**Comment by gracjankn** [comment] 2020-01-19 19:31
@romaincointepas Maybe add the ability to block **everything** Facebook related in one shot? I'd highly appreciate that, because I'm 100% off all Facebook services including Messenger, Instagram and Whatsapp.

A few example lists for that (they also block the "fbcdn.net" domain):
https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all
https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
https://gitlab.com/CHEF-KOCH/cks-filterlist/blob/master/Anti-Corp/filters/facebook.txt

They are mentioned on [pihole-google](https://github.com/nickspaargaren/pihole-google) that's available in NextDNS.

**Comment by gracjankn** [comment] 2020-01-20 08:36
> @romaincointepas Maybe add the ability to block **everything** Facebook related in **one shot**? I'd highly appreciate that, because I'm 100% off **all Facebook services** including Messenger, Instagram and Whatsapp.
> 
> A few **example lists** for that (they also block the "**fbcdn.net**" domain):
> https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all
> https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
> https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
> https://gitlab.com/CHEF-KOCH/cks-filterlist/blob/master/Anti-Corp/filters/facebook.txt
> 
> They are **mentioned** on [pihole-google](https://github.com/nickspaargaren/pihole-google) that's **available in NextDNS**.

I made a pull request for that, adding Anudeep's Facebook blocklist: https://github.com/nextdns/lists/pull/56

**Comment by s-crypt** [comment] 2020-02-09 10:33
@romaincointepas I can confirm that fbcdn.com blocks instagram services, unsure about messenger and whatsapp.

**Comment by romaincointepas** [comment] 2020-02-10 11:23
Closing, moving the discussion to https://github.com/nextdns/metadata/pull/56.

**Closed by romaincointepas** 2020-02-10 11:23 UTC
Labels: needs research
