### ISSUE TITLE
Please add List-KR

### ISSUE THREAD

**Issue by AndyH0ng** [nextdns/metadata#749] opened 2021-08-11 23:07 UTC
Youslist(which is already available) doesn’t block trackers from Korean website but List-KR does

https://github.com/List-KR/List-KR/raw/master/filter.txt

**Comment by hegdenischay** [comment] 2021-09-02 15:31
This is a duplicate of https://github.com/nextdns/metadata/issues/431.

**Closed** 2022-12-02 12:24 UTC
