### ISSUE TITLE
geni.us [false alarm]

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#558] opened 2021-01-30 10:49 UTC
![image](https://user-images.githubusercontent.com/19517680/106354309-7c93d380-6323-11eb-962c-371797dbfdca.png)

**Comment by beerisgood** [comment] 2021-01-30 11:13
Well, you see the problem: EasyPrivacy.
This isn't default NextDNS list, so you need report this false positive to EasyPrivacy dev.

**Comment by scafroglia93** [comment] 2021-03-18 09:41
@3xploiton3 
Use my setting for avoiding issue ->
https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

**Comment by romaincointepas** [comment] 2021-03-18 13:38
@scafroglia93 Please immediately stop telling people to use your NextDNS settings, and only comment when you can bring value to the issue.

**Comment by scafroglia93** [comment] 2021-03-18 13:46
> @scafroglia93 Please immediately stop telling people to use your NextDNS settings, and only comment when you can bring value to the issue.

I don't waste any more time, next time others will think about contacting the maintainer on duty

Most of the problems are caused by incorrect list combinations but, having said that, make it your own

**Comment by romaincointepas** [comment] 2021-06-12 11:47
Doesn't seem to be blocked anymore, closing.

**Closed by romaincointepas** 2021-06-12 11:47 UTC
