### ISSUE TITLE
Add a Spanish block list like AdGuard Spanish/Portuguese

### ISSUE THREAD

**Issue by sdgrs546547Q** [nextdns/metadata#801] opened 2021-11-01 20:35 UTC
There is no block list for Spanish content, so one is required. Some good recommendation would be those of AdGuard Spanish / Portuguese (https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_9_Spanish/filter.txt ) 

Thanks!

**Comment by romaincointepas** [comment] 2022-12-02 12:06
Duplicate of https://github.com/nextdns/blocklists/issues/18

**Closed by romaincointepas** 2022-12-02 12:06 UTC
